config/routes.rb
Rails.application.routes.draw do
  root 'home#show'
  namespace :app do
    root 'home#show'
    get '/auth/:provider/callback', to: 'sessions#create'
    resources :sessions, only: [:destroy]
    namespace :v1 do
      root 'home#show'
      get '/auth/:provider/callback', to: 'sessions#create'
      resources :sessions, only: [:destroy]
      get :sync, to:'sync#show'
    end
  end
  resources :settings, only: [:index, :create]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/setting.rb
class Setting < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_token :auth_token
  has_one :setting

  validates :uid, presence: true
  validates :provider, presence: true, uniqueness: { scope: :uid }
  validates_inclusion_of :contributor, in: [true, false]

  def self.find_or_create_from_auth_hash(auth_hash)
    User.find_or_create_by(uid: auth_hash.uid, provider: auth_hash.provider)
  end
end

app/controllers/app/home_controller.rb
class App::HomeController < ApplicationController
  def show
  end
end

app/controllers/app/sessions_controller.rb
module App
  class SessionsController < ApplicationController
    def create
      user = User.find_or_create_from_auth_hash(auth_hash)
      session[:auth_token] = user.auth_token
      SetPatreonContributorsJob.perform_later
      SetGithubContributorsJob.perform_later
      redirect_to app_root_path
    end

    def destroy
      session[:auth_token] = nil
      redirect_to app_root_path
    end

    private

    def auth_hash
      request.env['omniauth.auth']
    end
  end
end

app/controllers/app/v1/home_controller.rb
class App::V1::HomeController < ApplicationController
  def show
    @provider = params[:provider]
  end
end

app/controllers/app/v1/sessions_controller.rb
module App
  module V1
    class SessionsController < ApplicationController
      def create
        user = User.find_or_create_from_auth_hash(auth_hash)
        session[:auth_token] = user.auth_token
        SetPatreonContributorsJob.perform_later
        SetGithubContributorsJob.perform_later
        redirect_to app_v1_root_path
      end

      def destroy
        session[:auth_token] = nil
        redirect_to app_v1_root_path
      end

      private

      def auth_hash
        request.env['omniauth.auth']
      end
    end
  end
end

app/controllers/app/v1/sync_controller.rb
class App::V1::SyncController < ApplicationController
  def show
    redirect_to app_v1_root_path unless current_user
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user, :logged_in?, :contributor?

  private

  def current_user
    @current_user ||= User.find_by(auth_token: session[:auth_token]) \
      if session[:auth_token]
  end

  def logged_in?
    current_user != nil
  end

  def contributor?
    logged_in? && current_user.contributor
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def show
  end
end

app/controllers/settings_controller.rb
class SettingsController < ApplicationController

  def index
    render json: current_user&.setting.as_json
  end

  def create
    if current_user.setting.present?
      current_user.setting.update(setting_params)
    else
      current_user.build_setting(setting_params).save
    end
  end

  private

  def setting_params
    params.require(:setting).permit(data: {})
  end
end

app/helpers/app/home_helper.rb
module App::HomeHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/app/home/show.html.erb
<section class="hero is-primary is-fullheight">
  <% if logged_in? %>
    <div class="hero-head">
      <nav class="column">
        <a href="<%= app_session_path(1) %>" data-method="delete" class="is-pulled-right button is-small is-primary is-inverted is-outlined">
          Logout
        </a>
      </nav>
    </div>
  <% end %>
  <div class="hero-body">
    <div data-controller="electron" class="container has-text-centered" data-electron-minimal-stretchly-version-value="<%= ENV['MIN_STRETCHLY_VERSION']%>">
      <div data-electron-target="hidden">
        Lost? Head
        <%= link_to "Home", root_path, class:"has-text-white has-text-weight-bold" %>.
      </div>
      <div data-electron-target="visible">
        <% if logged_in? %>
          <h1 class="title is-spaced is-size-1">
            Thank you!
          </h1>
          <h2 class="subtitle">
            Every month, it takes a lot of work to remind you to take a break.
            I hope Stretchly will help you lead more balanced life.
          </h2>
          <% if contributor? %>
            <div data-electron-target="unsupported">
              Looks like you are using an unsupported version of Stretchly. This might not work.
            </div>
            <a onclick="window.ElectronBridge.openContriborSettings()" class="button is-primary is-inverted is-outlined">
              Extra Settings
            </a>
          <% else %>
            <h2 class="subtitle">
              It seems that you are not a contributor, yet. If this is not correct,
              please, come back again later, as we are checking daily and
              every time you authenticate (and it might take a minute).
            </h2>
            <a onclick="window.ElectronBridge.openExternal('https://hovancik.net/stretchly/sponsor/')" class="button is-primary is-inverted is-outlined">
              <span class="icon is-small">
                <i class="fab fa-patreon"></i>
              </span>
              <span>Become a Patron</span>
            </a>
            <a href="<%= app_root_path %>" class="button is-primary is-inverted is-outlined">
              <span class="icon is-small">
                <i class="fas fa-heart"></i>
              </span>
              <span>I am contributor already</span>
            </a>
          <% end %>
        <% else %>
          <h1 class="title is-spaced is-size-1">
            Stretchly contributor?
          </h1>
          <h2 class="subtitle">
            There is something more you will get - apart from good
            feeling. More ways to personalize and get control on how
            the app works for you.
          </h2>
          <div data-controller="terms">
            <p class="buttons">
              <form>
                <button formaction="/app/auth/patreon" data-terms-target="auth" class="button is-primary is-inverted is-outlined">
                  <span class="icon is-small">
                    <i class="fab fa-patreon"></i>
                  </span>
                  <span>Authenticate with Patreon</span>
                </button>
              </form>
              <form>
                <button formaction="/app/auth/github" data-terms-target="auth" class="button is-primary is-inverted is-outlined">
                  <span class="icon is-small">
                    <i class="fab fa-github"></i>
                  </span>
                  <span>Authenticate with Github</span>
                </button>
              </form>
            </p>
            <label class="checkbox is-large">
              <input type="checkbox" data-terms-target="checkbox" data-action="terms#setDisabled">
              I agree to the
              <a class="has-text-white has-text-weight-bold" onclick="window.ElectronBridge.openExternal('https://github.com/hovancik/stretchly_server/blob/trunk/TERMS.md')">Terms and Conditions</a>
              and
              <a class="has-text-white has-text-weight-bold" onclick="window.ElectronBridge.openExternal('https://github.com/hovancik/stretchly_server/blob/trunk/PRIVACY.md')">Privacy Policy</a>.
            </label>
          </div>
        <% end %>
      </div>
    </div>
  </div>
  <%= render "shared/footer" %>
</section>

app/views/app/v1/home/show.html.erb
<section class="hero is-light is-fullheight">
  <% if logged_in? %>
    <div class="hero-head">
      <nav class="column">
        <a href="<%= app_v1_session_path(1) %>" data-method="delete" class="is-pulled-right button is-small is-light is-inverted is-outlined">
          Logout
        </a>
      </nav>
    </div>
  <% end %>
  <div class="hero-body">
    <div data-controller="electron" class="container has-text-centered" data-electron-minimal-stretchly-version-value="<%= ENV['MIN_STRETCHLY_VERSION']%>">
      <div data-electron-target="hidden">
        Lost? Head
        <%= link_to "Home", root_path %>.
      </div>
      <div data-electron-target="visible">
        <% if logged_in? %>

          <% if contributor? %>
            <h1 class="title is-spaced is-size-1">
              Thank you!
            </h1>
            <h2 class="subtitle">
              Every month, it takes a lot of work to remind you to take a break.
              I hope Stretchly will help you lead more balanced life.
            </h2>
            <div data-electron-target="unsupported" class="notification is-warning has-text-left">
              Looks like you are using an unsupported version of Stretchly. This might not work.
            </div>
            <script type="text/javascript">
              window.ElectronBridge.setContributor()
            </script>
            <a onclick="window.ElectronBridge.showContributorPreferences()" class="button is-light is-inverted is-outlined">
              <span class="icon is-small">
                <i class="fas fa-user-cog"></i>
              </span>
              <span>Contributor Preferences</span>
            </a>
            <a href="<%= app_v1_sync_path %>" class="button is-light is-inverted is-outlined">
              <span class="icon is-small">
                <i class="fas fa-sync"></i>
              </span>
              <span>Sync Preferences</span>
            </a>
          <% else %>
            <h2 class="subtitle">
              It seems that you are not a contributor, yet. If this is not correct,
              please, come back again later, as we are checking daily and
              every time you authenticate (and it might take a minute).
            </h2>
            <a onclick="window.ElectronBridge.openExternal('https://hovancik.net/stretchly/sponsor/')" class="button is-light is-inverted is-outlined">
              <span class="icon is-small">
                <i class="fab fa-patreon"></i>
              </span>
              <span>Become a Patron</span>
            </a>
            <a href="<%= app_v1_root_path %>" class="button is-light is-inverted is-outlined">
              <span class="icon is-small">
                <i class="fas fa-heart"></i>
              </span>
              <span>I am contributor already</span>
            </a>
          <% end %>
        <% else %>
          <h1 class="title is-spaced is-size-1">
            Stretchly contributor?
          </h1>
          <h2 class="subtitle">
            There is something more you will get - apart from good
            feeling. More ways to personalize and get control on how
            the app works for you.
          </h2>
          <div data-controller="terms">
            <p class="buttons">
              <% if @provider == 'patreon' || @provider.nil? %>
                <form>
                  <button formaction="/app/v1/auth/patreon" data-terms-target="auth" class="button is-light is-inverted is-outlined">
                    <span class="icon is-small">
                      <i class="fab fa-patreon"></i>
                    </span>
                    <span>Continue with Patreon</span>
                  </button>
                </form>
              <% end %>
              <% if @provider == 'github' || @provider.nil? %>
                <form>
                  <button formaction="/app/v1/auth/github" data-terms-target="auth" class="button is-light is-inverted is-outlined">
                    <span class="icon is-small">
                      <i class="fab fa-github"></i>
                    </span>
                    <span>Continue with Github</span>
                  </button>
                </form>
              <% end %>
            </p>
            <label class="checkbox is-large">
              <input type="checkbox" data-terms-target="checkbox" data-action="terms#setDisabled">
              I agree to the
              <a onclick="window.ElectronBridge.openExternal('https://github.com/hovancik/Stretchly_server/blob/trunk/TERMS.md')">Terms and Conditions</a>
              and
              <a onclick="window.ElectronBridge.openExternal('https://github.com/hovancik/Stretchly_server/blob/trunk/PRIVACY.md')">Privacy Policy</a>.
            </label>
          </div>
        <% end %>
      </div>
    </div>
  </div>
  <%= render "shared/footer_v1" %>
</section>

app/views/app/v1/sync/show.html.erb
<section class="hero is-light is-fullheight">
  <% if logged_in? %>
    <div class="hero-head">
      <nav class="column">
        <a href="<%= app_v1_session_path(1) %>" data-method="delete" class="is-pulled-right button is-small is-light is-inverted is-outlined">
          Logout
        </a>
      </nav>
    </div>
  <% end %>
  <div class="hero-body ">
    <div data-controller="electron" class="container" data-electron-minimal-stretchly-version-value="<%= ENV['MIN_STRETCHLY_VERSION']%>">
      <div data-electron-target="hidden">
        Lost? Head
        <%= link_to "Home", root_path %>.
      </div>
      <div data-electron-target="visible">
        <% if logged_in? && contributor? %>
          <h1 class="title">Sync Preferences</h1>
          <div data-electron-target="unsupported" class="notification is-warning">
            Looks like you are using an unsupported version of Stretchly. This might not work.
          </div>
          <div class="content">
            <p>
              When there are differences between your Local Preferences
              and Remote ones, you'll see them below.
              Local Preferences are <span class="has-text-primary">green</span>,
              Remote are <span class="has-text-info">blue</span>.
            </p>
            <p>
              If anything goes wrong, remove Stretchly preferences file
              and restart Stretchly to get the default ones.
            </p>
          </div>
          <div data-controller="sync">
            <div class="buttons">
              <%= form_with do %>
                <a data-action="click->sync#backup" class="button is-primary">Backup</a>
                <% if current_user.setting.present? %>
                  <a data-action="click->sync#restore" class="button is-info">Restore</a>
                <% end %>
                <%= link_to "Refresh Data", app_v1_sync_path, class: "button is-success"%>
              <% end %>
            </div>
            <div class="box">
              <span class="has-text-primary">Local Preferences</span> <br/>
              <% if current_user.setting.present? %>
                <span class="has-text-info">Remote Preferences, last backed up at <%= current_user.setting.updated_at %></span>
              <% else %>
                <span class="has-text-info">Remote Preferences, never backed up</span>
              <% end %>
            </div>
            <div id="settings" class="content">

            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
  <%= render "shared/footer_v1" %>
</section>

app/views/home/show.html.erb
<section class="hero is-light is-fullheight">
  <div class="hero-body">
    <div class="container has-text-left">
      <div class="columns is-vcentered">
        <div class="column is-8">
          <h1 class="title is-spaced is-size-1">
            Love your Stretchly?
          </h1>
          <h2 class="subtitle">
            Taking regular breaks and microbreaks makes you more effective -
            that is science. But only you know your flow.
            Support Stretchly by becoming a contributor and simplify
            your access to the settings that let you customize your breaks even more.
          </h2>
          <div data-controller="electron">
            <div data-electron-target="visible" class="buttons are-medium">
              <a onclick="window.ElectronBridge.openExternal('https://hovancik.net/stretchly/sponsor/')" class="button is-light is-inverted is-outlined">
                <span class="icon is-small">
                  <i class="fab fa-patreon"></i>
                </span>
                <span>Become a Patron</span>
              </a>
              <a href="<%= app_root_path %>" class="button is-light is-inverted is-outlined">
                <span class="icon is-small">
                  <i class="fas fa-heart"></i>
                </span>
                <span>I am contributor already</span>
              </a>
            </div>
            <div data-electron-target="hidden" class="buttons are-medium">
              <a href="https://hovancik.net/stretchly/sponsor/" class="button is-light is-inverted is-outlined">
                <span class="icon is-small">
                  <i class="fab fa-patreon"></i>
                </span>
                <span>Become a Patron</span>
              </a>
            </div>
          </div>
        </div>
        <div class="column is-4">
          <figure class="image is-square">
            <img src="/stretchly.png">
          </figure>
        </div>
      </div>
    </div>
  </div>
  <%= render "shared/footer_v1" %>
</section>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Your Stretchly</title>
    <meta name="flattr:id" content="en32oj">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://fonts.googleapis.com/css?family=Open+Sans&display=swap" rel="stylesheet">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
    <%= javascript_pack_tag 'application' %>
    <%= stylesheet_pack_tag 'application' %>
    <!-- Matomo -->
    <script type="text/javascript">
      var _paq = _paq || [];
      /* tracker methods like "setCustomDimension" should be called before "trackPageView" */
      _paq.push(['trackPageView']);
      _paq.push(['enableLinkTracking']);
      (function() {
        var u="https://stats.hovancik.net/";
        _paq.push(['setTrackerUrl', u+'piwik.php']);
        _paq.push(['setSiteId', '6']);
        var d=document, g=d.createElement('script'), s=d.getElementsByTagName('script')[0];
        g.type='text/javascript'; g.async=true; g.defer=true; g.src=u+'piwik.js'; s.parentNode.insertBefore(g,s);
      })();
    </script>
    <!-- End Matomo Code -->
  </head>
  <body>
    <%= yield %>
  </body>
</html>

app/views/shared/_footer.html.erb
<div class="hero-foot">
  <div class="container">
    <!-- Begin MailChimp Signup Form -->
    <div id="mc_embed_signup" class="column">
      <form action="//stretchly.us11.list-manage.com/subscribe/post?u=7ce75bb5ad016b05238a9a095&amp;id=49efaa672f" method="post" id="mc-embedded-subscribe-form" name="mc-embedded-subscribe-form" class="validate" target="_blank" novalidate="">
        <div id="mc_embed_signup_scroll">
          <div class="field is-grouped is-grouped-centered is-grouped-multiline">
            <div class="control has-icons-left">
              <input class="input" name="EMAIL" type="text" id="mce-EMAIL" placeholder="email address" required="">
              <span class="icon is-small is-left">
                <i class="fa fa-envelope"></i>
              </span>
            </div>
            <!-- real people should not fill this in and expect good things - do not remove this or risk form bot signups-->
            <div style="position: absolute; left: -5000px;" aria-hidden="true"><input type="text" name="b_7ce75bb5ad016b05238a9a095_49efaa672f" tabindex="-1" value=""></div>
            <div class="control">
              <input type="submit" value="subscribe to newsletter" name="subscribe" id="mc-embedded-subscribe" class="button is-primary is-inverted is-outlined">
            </div>
          </div>
        </div>
      </form>
    </div>
    <!--End mc_embed_signup-->
  </div>
</div>

app/views/shared/_footer_v1.html.erb
<div class="hero-foot">
  <div class="container">
    <!-- Begin MailChimp Signup Form -->
    <div id="mc_embed_signup" class="column">
      <form action="//stretchly.us11.list-manage.com/subscribe/post?u=7ce75bb5ad016b05238a9a095&amp;id=49efaa672f" method="post" id="mc-embedded-subscribe-form" name="mc-embedded-subscribe-form" class="validate" target="_blank" novalidate="">
        <div id="mc_embed_signup_scroll">
          <div class="field is-grouped is-grouped-centered is-grouped-multiline">
            <div class="control has-icons-left">
              <input class="input" name="EMAIL" type="text" id="mce-EMAIL" placeholder="email address" required="">
              <span class="icon is-small is-left">
                <i class="fa fa-envelope"></i>
              </span>
            </div>
            <!-- real people should not fill this in and expect good things - do not remove this or risk form bot signups-->
            <div style="position: absolute; left: -5000px;" aria-hidden="true"><input type="text" name="b_7ce75bb5ad016b05238a9a095_49efaa672f" tabindex="-1" value=""></div>
            <div class="control">
              <input type="submit" value="subscribe to newsletter" name="subscribe" id="mc-embedded-subscribe" class="button is-light is-inverted is-outlined">
            </div>
          </div>
        </div>
      </form>
    </div>
    <!--End mc_embed_signup-->
  </div>
</div>